export default {
  NOTIFICATION_REQUEST: "NOTIFICATION_REQUEST",
  NOTIFICATION_SUCCESS: "NOTIFICATION_SUCCESS",
  NOTIFICATION_FAILED: "NOTIFICATION_FAILED",

  FOLLOWERS_REQUEST: "FOLLOWERS_REQUEST",
  FOLLOWERS_SUCCESS: "FOLLOWERS_SUCCESS",
  FOLLOWERS_FAILED: "FOLLOWERS_FAILED",
};
