// CONFIGURE REDUX ACTIONS TYPES

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const SET_ONE_SIGNAL_ID = "SET_ONE_SIGNAL_ID";
export const SET_SELECTED_LANGUAGE = "SET_SELECTED_LANGUAGE"; // to change language in the app

export const SET_IS_GUEST = "SET_IS_GUEST";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SET_USER_CONVER = "SET_USER_CONVER";

export const REFRESH_REQUEST = "REFRESH_REQUEST";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAILED = "REFRESH_FAILED";

export const SET_CURRENT_USER_NOTIFICATION_PERMISSION = "SET_CURRENT_USER_NOTIFICATION_PERMISSION";

export const SET_CURRENT_USER_ADHERENT_CARD = "SET_CURRENT_USER_ADHERENT_CARD";
