export default {
  LIST_REQUEST: "LIST_REQUEST",
  LIST_SUCCESS: "LIST_SUCCESS",
  LIST_FAILED: "LIST_FAILED",

  GET_ONE_REQUEST: "GET_ONE_REQUEST",
  GET_ONE_SUCCESS: "GET_ONE_SUCCESS",
  GET_ONE_FAILED: "GET_ONE_FAILED",
};
