require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'SNPINews' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  # target 'SNPINewsTests' do
  #   inherit! :complete*
  #   # Pods for testing
  # end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
    
 post_install do |installer|
     react_native_post_install(installer)
     __apply_Xcode_12_5_M1_post_install_workaround(installer)
      # This is necessary for Xcode 14, because it signs resource bundles by default
         # when building for devices.
         installer.target_installation_results.pod_target_installation_results
           .each do |pod_name, target_installation_result|
           target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
             resource_bundle_target.build_configurations.each do |config|
               config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
             end
           end
         end
         installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
             config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
           end
         end
   end
  
  `sed -i -e  $'s/__IPHONE_12_0/__IPHONE_14_0/' Pods/RCT-Folly/folly/portability/Time.h`
end


# wonder push config 
target 'WonderPushNotificationServiceExtension' do

  # Pods for WonderPushNotificationServiceExtension
  pod 'WonderPushExtension', '~> 4.0'
end
