import {I18nManager} from 'react-native';
import strings from './strings';

export const WITH_SOCIAL = false;

export const AUTHENTICATION_TYPE = 'basic'; //enum (BASIC, PHONE, NONE)

export const GOOGLE_API_KEY = 'AIzaSyBXWOxwBiZNJf_cTQ3NwieZfZhJrH4lPJg';

export const GENDER = [
  {value: 'm', label: 'man'},
  {value: 'f', label: 'woman'},
];

export const DEFAULT_BIRTHDATE = new Date(1992, 2, 1); //01/03/1992

export const CONTACTS = {
  email: 'info@cosmind.co',
  phone: '+212 6 61 24 33 56',
  whatsapp: '212661243356',
};

export const CITIESAr = [
  {value: 'ARFOUD (ERFOUD)', label: 'أرفود'},
  {value: 'ASILAH', label: 'أصيلة'},
  {value: 'IFRANE', label: 'افران'},
  {value: 'DAKHLA', label: 'الداخلة'},
  {value: 'EL JADIDA', label: 'الجديدة'},
  {value: 'CASABLANCA', label: 'الدار البيضاء'},
  {value: 'Errachidia', label: 'الرشيدية'},
  {value: 'NADOR', label: 'الناظور'},
  {value: 'RABAT', label: 'الرباط'},
  {value: 'SKHIRAT', label: 'الصخيرات'},
  {value: 'SAIDIA', label: 'السعيدية'},
  {value: 'LARACHE', label: 'العرائش'},
  {value: 'ESSAOUIRA', label: 'الصويرة'},
  {value: 'MOHAMMEDIA', label: 'المحمدية'},
  {value: 'KENITRA', label: 'القنيطرة'},
  {value: 'KHEMISSET', label: 'الخميسات'},
  {value: 'LAAYOUNE', label: 'العيون'},
  {value: 'FNIDEQ', label: 'الفنيدق'},
  {value: 'HARHOURA', label: 'الهرهورة'},
  {value: 'AL HOUCEIMA', label: 'الحسيمة'},
  {value: 'INEZGANE', label: 'انزكان'},
  {value: 'SAFI', label: 'أسفي'},
  {value: 'BERKANE', label: 'بركان'},
  {value: 'BERRECHID', label: 'برشيد'},
  {value: 'BEN SLIMANE', label: 'بنسليمان'},
  {value: 'BENI MELLAL', label: 'بني ملال'},
  {value: 'BOUZNIKA', label: 'بوزنيقة'},
  {value: 'Bouskoura', label: 'بوسكورة'},
  {value: 'TAZA', label: 'تازة'},
  {labvalueel: 'TAOUNAT', label: 'تونات'},
  {value: 'TAROUDANNT', label: 'تارودانت'},
  {value: 'TEMARA', label: 'تمارة'},
  {value: 'TETOUAN', label: 'تطوان'},
  {value: 'TIFLET', label: 'تيفلت'},
  {value: 'TIZNIT', label: 'تزنيت'},
  {value: 'KHENIFRA', label: 'خنيفرة'},
  {value: 'KHOURIBGA', label: 'خريبكة'},
  {value: 'ZAGORA', label: 'زاكورة'},
  {value: 'SALE', label: 'سلا'},
  {value: 'SETTAT', label: 'سطات'},
  {value: 'SIDI KACEM', label: 'سيدي قاسم'},
  {value: 'SIDI SLIMANE', label: 'سيدي سليمان'},
  {value: 'CHEFCHAOUEN', label: 'شفشاون'},
  {value: 'SEFROU', label: 'صفرو'},
  {value: 'TANGER', label: 'طنجة'},
  {value: 'TAN TAN', label: 'طانطان'},
  {value: 'TARFAYA', label: 'طرفاية'},
  {value: 'TATA', label: 'طاطا'},
  {value: 'AIN EL AOUDA', label: 'عين عودة'},
  {value: 'FES', label: 'فاس'},
  {value: 'FIGUIG', label: 'فكيك'},
  {value: 'LAGOUIRA', label: 'لغويرة'},
  {value: 'MARRAKECH', label: 'مراكش'},
  {value: 'MARTIL', label: 'مرتيل'},
  {value: 'MEKNES', label: 'مكناس'},
  {value: 'MIDELT', label: 'ميدلت'},
  {value: 'OUARZAZATE', label: 'ورزازات'},
  {value: 'OUEZZANE', label: 'وزان'},
  {value: 'OUJDA', label: 'وجدة'},
];
export const CITIESFr = [
  {label: 'AIN EL AOUDA', value: 'AIN EL AOUDA'},
  {label: 'AL HOUCEIMA', value: 'AL HOUCEIMA'},
  {label: 'ARFOUD (ERFOUD)', value: 'ARFOUD (ERFOUD)'},
  {label: 'ASILAH', value: 'ASILAH'},
  {label: 'BENI MELLAL', value: 'BENI MELLAL'},
  {label: 'BEN SLIMANE', value: 'BEN SLIMANE'},
  {label: 'BERKANE', value: 'BERKANE'},
  {label: 'BERRECHID', value: 'BERRECHID'},
  {label: 'Bouskoura', value: 'Bouskoura'},
  {label: 'BOUZNIKA', value: 'BOUZNIKA'},
  {label: 'CASABLANCA', value: 'CASABLANCA'},
  {label: 'CHEFCHAOUEN', value: 'CHEFCHAOUEN'},
  {label: 'DAKHLA', value: 'DAKHLA'},
  {label: 'EL JADIDA', value: 'EL JADIDA'},
  {label: 'Errachidia', value: 'Errachidia'},
  {label: 'ESSAOUIRA', value: 'ESSAOUIRA'},
  {label: 'FES', value: 'FES'},
  {label: 'FIGUIG', value: 'FIGUIG'},
  {label: 'FNIDEQ', value: 'FNIDEQ'},
  {label: 'HARHOURA', value: 'HARHOURA'},
  {label: 'IFRANE', value: 'IFRANE'},
  {label: 'INEZGANE', value: 'INEZGANE'},
  {label: 'KENITRA', value: 'KENITRA'},
  {label: 'KHEMISSET', value: 'KHEMISSET'},
  {label: 'KHENIFRA', value: 'KHENIFRA'},
  {label: 'KHOURIBGA', value: 'KHOURIBGA'},
  {label: 'LAAYOUNE', value: 'LAAYOUNE'},
  {label: 'LAGOUIRA', value: 'LAGOUIRA'},
  {label: 'LARACHE', value: 'LARACHE'},
  {label: 'MARRAKECH', value: 'MARRAKECH'},
  {label: 'MARTIL', value: 'MARTIL'},
  {label: 'MEKNES', value: 'MEKNES'},
  {label: 'MIDELT', value: 'MIDELT'},
  {label: 'MOHAMMEDIA', value: 'MOHAMMEDIA'},
  {label: 'NADOR', value: 'NADOR'},
  {label: 'OUARZAZATE', value: 'OUARZAZATE'},
  {label: 'OUEZZANE', value: 'OUEZZANE'},
  {label: 'OUJDA', value: 'OUJDA'},
  {label: 'RABAT', value: 'RABAT'},
  {label: 'SAFI', value: 'SAFI'},
  {label: 'SAIDIA', value: 'SAIDIA'},
  {label: 'SALE', value: 'SALE'},
  {label: 'SEFROU', value: 'SEFROU'},
  {label: 'SETTAT', value: 'SETTAT'},
  {label: 'SIDI KACEM', value: 'SIDI KACEM'},
  {label: 'SIDI SLIMANE', value: 'SIDI SLIMANE'},
  {label: 'SKHIRAT', value: 'SKHIRAT'},
  {label: 'TANGER', value: 'TANGER'},
  {label: 'TAN TAN', value: 'TAN TAN'},
  {label: 'TAOUNAT', value: 'TAOUNAT'},
  {label: 'TARFAYA', value: 'TARFAYA'},
  {label: 'TAROUDANNT', value: 'TAROUDANNT'},
  {label: 'TATA', value: 'TATA'},
  {label: 'TAZA', value: 'TAZA'},
  {label: 'TEMARA', value: 'TEMARA'},
  {label: 'TETOUAN', value: 'TETOUAN'},
  {label: 'TIFLET', value: 'TIFLET'},
  {label: 'TIZNIT', value: 'TIZNIT'},
  {label: 'ZAGORA', value: 'ZAGORA'},
];
